### ISSUE TITLE
Basic Nette commands

### ISSUE THREAD

**Issue by fprochazka** [Kdyby/Console#7]
- [ ] clear cache
- [ ] maintenance mode switch (how would it switch back?)
- [ ] archive-logs (would remove `email-sent` and create timestamp directory and move all current log files there)

What else do you have in mind?

**Comment by juniwalk** [comment]
@fprochazka This is what I use in cli-config.php for Doctrine commands:
```php
// Load Nette DI container instance and get EntityManager
$di = include __DIR__.'/../app/bootstrap.php';
$em = $di->getByType('Kdyby\Doctrine\EntityManager');
```
Which warms up cache, atleast for Doctrine, would it help if you get Application service and run it in the command? So you would not need to know the Url of the site?

Just correct me if I am wrong, my knowledge of Nette is not that great yet.

**Comment by juniwalk** [comment]
Also add command to **fix permissions**, this is something I use a lot!

I have created tiny CLI application [juniwalk/darwin](https://github.com/juniwalk/Darwin) to do just that, but it still needs some work on that fix command - viz juniwalk/darwin#1.

**Comment by fprochazka** [comment]
@juniwalk I don't think this package should contain commands for doctrine

**Comment by juniwalk** [comment]
@fprochazka that was just example, you would put code from index.php there, meaning:
```php
// Load Nette DI container instance and run Application service
$dic = include __DIR__.'/../app/bootstrap.php';
$dic->getByType('Nette\Application\Application')->run();
```
Thats for the cache warm up.

**Comment by Buri** [comment]
Regarding generation of container, easiest would be to spawn child process and run it with different temp folder. Nette will automatically generate the container and you could then run latte or do a dummy request to presenter in console. When cache is warmed up, just rename old folder, rename new folder and then delete the old folder.

Changing temp folder can be bit tricky, because by default its hardcoded in most examples. Options are:
- app needs to expecting temp directory from external source (IMO not really good way)
- chroot child process to another directory ([http://php.net/manual/en/function.chroot.php](url), works only on unix systems)

**Comment by fprochazka** [comment]
Well, I don't wanna do this now and definitely not as a part of this repository. If anything, they should be in separate package, independent of Kdyby/Console.

If you wanna help, go check out this issue @f3l1x opened https://github.com/contributte/console/issues/3, he promised not to make it tightly coupled with contributte/console :)

**Comment by f3l1x** [comment]
For the record, we have made it. There is a new package [contributte/console-extra](https://github.com/contributte/console-extra) with few useful Nette-based commands.

Check it out.
